### ISSUE TITLE
Win 10下使用这个输入法会强制把英语（美国）给带出来并且导致去除不掉

### ISSUE THREAD

**Issue by ted423** [lotem/rime-gits#10]
这时语言那一栏是没有英语（美国）的，但是右下角点一下仍然会显示切换到英语（美国）
必须先把输入法切到搜狗或者其他，然后把英语（美国）添加再删除后，才能把英语（美国）给删掉

试了下，Win7也有这个问题

**Comment by Hug125** [comment]
可以看一下Win10的语言列表，将语言列表中的英语删掉之后也不会自动出现英语(美国)。

**Comment by ted423** [comment]
> 可以看一下Win10的语言列表，将语言列表中的英语删掉之后也不会自动出现英语(美国)。

我之前装的时候是没有的，但只要安装输入法或者怎么操作一下就会带出来

**Comment by ted423** [comment]
最新版没有问题
